# Generated by Django 2.2.7 on 2020-01-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200104_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='address',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='room',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='room',
            name='country',
        ),
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='room',
            name='house_rules',
        ),
        migrations.RemoveField(
            model_name='room',
            name='instant_book',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='equip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='intro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='sns',
            field=models.URLField(blank=True),
        ),
    ]
