# Generated by Django 2.2.7 on 2020-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='avatar',
        ),
    ]
