# Generated by Django 2.2.7 on 2020-01-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='accuracy',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cleanliness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location',
        ),
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
    ]
